### ISSUE TITLE
Getting overlay exception 

### ISSUE THREAD

**Issue by akshayru** [doonfrs/hover_menu#1]
I am getting overlay state exception when i am running the example provided with plugin as is. 
```
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/hover_menu-1.0.1+1/lib/hover_menu.dart:41:27: Error: Method 'insert' cannot be called on 'OverlayState?' because it is potentially null.
- 'OverlayState' is from 'package:flutter/src/widgets/overlay.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/overlay.dart').
overlay.dart:1
Try calling using ?. instead.
      Overlay.of(context).insert(_overlayEntry!);
                          ^^^^^^
```

**Comment by akshayru** [comment]
If i update line 41 in hover_menu class by adding "?" it does resolve the issue. Just sharing it so you can fix the plugin and I don't have to use custom code.
`       Overlay.of(context)?.insert(_overlayEntry!);`

**Comment by doonfrs** [comment]
Please make sure the SDK is 
  sdk: '>=2.19.0 <3.0.0'

**Comment by doonfrs** [comment]
Please try to upgrade Flutter.
What version do you have?
Because it is not nullable in the latest version:

![image](https://user-images.githubusercontent.com/4661009/233811490-f498acb4-fc19-486c-a5cf-728129293e16.png)
