### ISSUE TITLE
Mobile version Android doesn't work

### ISSUE THREAD

**Issue by akshayru** [doonfrs/hover_menu#2]
While Web Version of App works perfectly fine, the mobile version doesn't work or perform any action after navigation.

**Comment by doonfrs** [comment]
Hi akshayru.
It is not designed for mobile; using the regular drawer and the appBar for mobile and using hover_menu for desktop/web or wide screens, in general, is recommended.
You can use the if condition or visibility widget to achieve that.
I will update the readme for that.
